import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Typography, Grid, Card, CardContent, CardMedia, CardActionArea, Chip, Divider, FormControlLabel, Radio, RadioGroup, FormControl, FormLabel, Paper, } from "@mui/material";
import StarIcon from "@mui/icons-material/Star";
import ConfirmationNumberIcon from "@mui/icons-material/ConfirmationNumber";
import VpnKeyIcon from "@mui/icons-material/VpnKey";
import GroupIcon from "@mui/icons-material/Group";
import PersonIcon from "@mui/icons-material/Person";
import { TicketType } from "@/lib/types";
const TicketTypeSelection = ({ purchaseData, updatePurchaseData }) => {
    const handleTicketTypeChange = (event) => {
        updatePurchaseData({
            ticketType: event.target.value,
            isVIP: event.target.value === TicketType.VIP,
        });
    };
    return (_jsxs(Box, { children: [_jsx(Typography, { variant: "h5", gutterBottom: true, children: "Select Ticket Type" }), _jsx(Typography, { variant: "body1", paragraph: true, children: "Choose the type of ticket that best suits your visit to our museum. We offer different options to enhance your experience." }), _jsxs(FormControl, { component: "fieldset", sx: { mb: 4, width: "100%" }, children: [_jsx(FormLabel, { component: "legend", children: "Ticket Options" }), _jsx(RadioGroup, { "aria-label": "ticket-type", name: "ticket-type", value: purchaseData.ticketType, onChange: handleTicketTypeChange, children: _jsxs(Grid, { container: true, spacing: 3, sx: { mt: 1 }, children: [_jsx(Grid, { item: true, xs: 12, md: 6, children: _jsx(Paper, { variant: "outlined", sx: {
                                            p: 2,
                                            border: purchaseData.ticketType === TicketType.REGULAR ? 2 : 1,
                                            borderColor: purchaseData.ticketType === TicketType.REGULAR
                                                ? "primary.main"
                                                : "divider",
                                        }, children: _jsx(FormControlLabel, { value: TicketType.REGULAR, control: _jsx(Radio, {}), label: _jsxs(Box, { children: [_jsxs(Typography, { variant: "h6", component: "div", children: ["Regular Ticket", _jsx(ConfirmationNumberIcon, { sx: { ml: 1, verticalAlign: "middle" } })] }), _jsx(Typography, { variant: "body2", color: "text.secondary", children: "Standard museum access with all permanent exhibitions" }), _jsxs(Box, { sx: { mt: 2 }, children: [_jsx(Chip, { label: "Basic Access", size: "small", sx: { mr: 1, mb: 1 } }), _jsx(Chip, { label: "Permanent Exhibitions", size: "small", sx: { mr: 1, mb: 1 } })] }), _jsx(Typography, { variant: "h6", color: "primary", sx: { mt: 2 }, children: "$15.00" })] }), sx: { width: "100%", alignItems: "flex-start", m: 0 } }) }) }), _jsx(Grid, { item: true, xs: 12, md: 6, children: _jsx(Paper, { variant: "outlined", sx: {
                                            p: 2,
                                            border: purchaseData.ticketType === TicketType.VIP ? 2 : 1,
                                            borderColor: purchaseData.ticketType === TicketType.VIP
                                                ? "primary.main"
                                                : "divider",
                                        }, children: _jsx(FormControlLabel, { value: TicketType.VIP, control: _jsx(Radio, {}), label: _jsxs(Box, { children: [_jsxs(Typography, { variant: "h6", component: "div", children: ["VIP Ticket", _jsx(StarIcon, { sx: { ml: 1, verticalAlign: "middle", color: "gold" } })] }), _jsx(Typography, { variant: "body2", color: "text.secondary", children: "Premium access with special exhibitions and guided tour" }), _jsxs(Box, { sx: { mt: 2 }, children: [_jsx(Chip, { label: "Premium Access", size: "small", color: "primary", sx: { mr: 1, mb: 1 } }), _jsx(Chip, { label: "Special Exhibitions", size: "small", color: "primary", sx: { mr: 1, mb: 1 } }), _jsx(Chip, { label: "Guided Tour", size: "small", color: "primary", sx: { mr: 1, mb: 1 } }), _jsx(Chip, { label: "Priority Entry", size: "small", color: "primary", sx: { mr: 1, mb: 1 } })] }), _jsx(Typography, { variant: "h6", color: "primary", sx: { mt: 2 }, children: "$30.00" })] }), sx: { width: "100%", alignItems: "flex-start", m: 0 } }) }) })] }) })] }), _jsx(Divider, { sx: { my: 4 } }), _jsx(Typography, { variant: "h6", gutterBottom: true, children: "Popular Packages" }), _jsxs(Grid, { container: true, spacing: 3, children: [_jsx(Grid, { item: true, xs: 12, md: 4, children: _jsx(Card, { children: _jsxs(CardActionArea, { onClick: () => updatePurchaseData({
                                    ticketType: TicketType.REGULAR,
                                    isVIP: false,
                                }), children: [_jsx(CardMedia, { component: "img", height: "180", sx: { objectFit: "contain" }, image: "/images/individual.png", alt: "Individual Package" }), _jsxs(CardContent, { children: [_jsxs(Typography, { gutterBottom: true, variant: "h6", component: "div", children: ["Individual Package", _jsx(PersonIcon, { sx: { ml: 1, verticalAlign: "middle" } })] }), _jsx(Typography, { variant: "body2", color: "text.secondary", children: "Perfect for solo visitors who want to explore at their own pace." }), _jsxs(Box, { sx: { mt: 2 }, children: [_jsx(Chip, { label: "1 Person", size: "small", sx: { mr: 1 } }), _jsx(Chip, { label: "Self-guided", size: "small" })] })] })] }) }) }), _jsx(Grid, { item: true, xs: 12, md: 4, children: _jsx(Card, { children: _jsxs(CardActionArea, { onClick: () => updatePurchaseData({
                                    ticketType: TicketType.REGULAR,
                                    isVIP: false,
                                }), children: [_jsx(CardMedia, { component: "img", height: "180", sx: { objectFit: "contain" }, image: "/images/couple.png", alt: "Family Package" }), _jsxs(CardContent, { children: [_jsxs(Typography, { gutterBottom: true, variant: "h6", component: "div", children: ["Family Package", _jsx(GroupIcon, { sx: { ml: 1, verticalAlign: "middle" } })] }), _jsx(Typography, { variant: "body2", color: "text.secondary", children: "Ideal for families with children, includes interactive exhibits." }), _jsxs(Box, { sx: { mt: 2 }, children: [_jsx(Chip, { label: "2-5 People", size: "small", sx: { mr: 1 } }), _jsx(Chip, { label: "Kid-friendly", size: "small" })] })] })] }) }) }), _jsx(Grid, { item: true, xs: 12, md: 4, children: _jsx(Card, { children: _jsxs(CardActionArea, { onClick: () => updatePurchaseData({ ticketType: TicketType.VIP, isVIP: true }), children: [_jsx(CardMedia, { component: "img", height: "180", sx: { objectFit: "contain" }, image: "/images/vip.png", alt: "VIP Experience" }), _jsxs(CardContent, { children: [_jsxs(Typography, { gutterBottom: true, variant: "h6", component: "div", children: ["VIP Experience", _jsx(VpnKeyIcon, { sx: { ml: 1, verticalAlign: "middle", color: "gold" } })] }), _jsx(Typography, { variant: "body2", color: "text.secondary", children: "Premium access with guided tour and exclusive exhibits." }), _jsxs(Box, { sx: { mt: 2 }, children: [_jsx(Chip, { label: "Premium", size: "small", color: "primary", sx: { mr: 1 } }), _jsx(Chip, { label: "Guided Tour", size: "small", color: "primary" })] })] })] }) }) })] })] }));
};
export default TicketTypeSelection;
